name: docker

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set env
        run: |
          echo "PLAKAR_SHA=$(git ls-remote https://github.com/poolpOrg/plakar  main | awk '{ print substr($1,1,7) }')" >> $GITHUB_ENV \
          && echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV \
          && echo "VCS_REF=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: barcus/plakar:latest
          build-args: |
            PLAKAR_SHA
            VCS_REF
            BUILD_DATE
      -
        name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3.0.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: barcus/plakar

