name: docker

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      -
        name: Build & Push
        run: |
          docker buildx build --push \
          --no-cache \
          --platform linux/amd64,linux/arm64 \
          --build-arg VERSION="beta" \
          --build-arg VCS_REF=$(git rev-parse --short HEAD) \
          --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
          --build-arg NAME="plakar" \
          --tag barcus/plakar:latest \
          .
